//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block_Master
    {
        public int BlockId_pk { get; set; }
        public Nullable<int> LG_Block_Code { get; set; }
        public Nullable<int> DistrictId_fk { get; set; }
        public string District { get; set; }
        public string Block { get; set; }
        public string FPCP_Block { get; set; }
        public Nullable<int> BlockId_pk1 { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual District_Master District_Master { get; set; }
    }
}
