//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contraceptive_Child_Master
    {
        public int ID { get; set; }
        public Nullable<int> CID { get; set; }
        public string MethodName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Contraceptive_Master Contraceptive_Master { get; set; }
    }
}
