//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panchayat_Master
    {
        public int Panchayatid_pk { get; set; }
        public Nullable<int> DistrictId_fk { get; set; }
        public Nullable<int> Blockid_fk { get; set; }
        public string Block { get; set; }
        public string Panchayat { get; set; }
        public string FPCP_Panchayat { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
