//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CLFPlanApprove
    {
        public System.Guid ApprovePlanId_pk { get; set; }
        public Nullable<System.Guid> PlanId_fk { get; set; }
        public Nullable<System.DateTime> ApprovalMonth { get; set; }
        public Nullable<System.DateTime> ApprovalYear { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
