//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Emp
    {
        public System.Guid EmpID_pk { get; set; }
        public string UserID_fk { get; set; }
        public string RoleID_fk { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> BlockID { get; set; }
        public Nullable<int> VOId_fk { get; set; }
        public Nullable<int> PanchayatId { get; set; }
        public string VillageName { get; set; }
        public string EmpName { get; set; }
        public string Gender { get; set; }
        public string MobileNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
