//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BFYFollowup
    {
        public System.Guid FollowupID_pk { get; set; }
        public Nullable<System.Guid> BFYID_fk { get; set; }
        public Nullable<int> FMonth { get; set; }
        public Nullable<int> FYear { get; set; }
        public Nullable<bool> IsFollowUp { get; set; }
        public Nullable<bool> IsContraception { get; set; }
        public Nullable<int> ContraceptionId_fk { get; set; }
        public Nullable<int> UseMethodId_fk { get; set; }
        public string ContraceptionOther { get; set; }
        public Nullable<int> ModuleRollout { get; set; }
        public Nullable<int> ModuleRolloutId_fk { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> Totalnoof_Femalechild { get; set; }
        public Nullable<int> Totalnoof_malechild { get; set; }
    }
}
