//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PaymentHistory
    {
        public System.Guid PaymentHistoryId_pk { get; set; }
        public string ApprovedAchvId { get; set; }
        public string RejectedAchvId { get; set; }
        public Nullable<int> NoofApproved { get; set; }
        public Nullable<int> NoofRejected { get; set; }
        public Nullable<System.Guid> VerifyUserTypeId { get; set; }
        public Nullable<System.Guid> TargetUserTypeId { get; set; }
        public Nullable<System.Guid> TargetUserId { get; set; }
        public Nullable<decimal> ClaimAmount { get; set; }
        public Nullable<decimal> ApprovedAmount { get; set; }
        public Nullable<int> PayMonth { get; set; }
        public Nullable<int> PayYear { get; set; }
        public string TypeofPayment { get; set; }
        public Nullable<decimal> MobilizationCNRP { get; set; }
        public Nullable<decimal> MobilizationCM { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
