//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CLF_Emp
    {
        public int ID { get; set; }
        public Nullable<System.Guid> EmpId_fk { get; set; }
        public Nullable<System.Guid> UserId_fk { get; set; }
        public Nullable<int> CLFIdfk { get; set; }
    }
}
