//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Achievement_Log
    {
        public System.Guid LogId_pk { get; set; }
        public Nullable<System.Guid> AchieveId_fk { get; set; }
        public Nullable<int> PlanStatus { get; set; }
        public Nullable<System.DateTime> PlanStatusDate { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
